"""Hash user passwords

Revision ID: bc878764dfa4
Revises: add_m3u_sources
Create Date: 2025-11-09 13:40:32.470785

"""
from alembic import op
import sqlalchemy as sa
import bcrypt
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = 'bc878764dfa4'
down_revision = 'add_m3u_sources'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add password_hash as nullable=True initially
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))

    # Define a temporary table representation for the 'users' table
    users_table = table(
        'users',
        column('id', sa.Integer),
        column('password', sa.String),
        column('password_hash', sa.String)
    )

    # Fetch all existing users and hash their passwords
    connection = op.get_bind()
    for user in connection.execute(sa.select(users_table.c.id, users_table.c.password)):
        if user.password:
            hashed_password = bcrypt.hashpw(user.password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
            op.execute(
                users_table.update().
                where(users_table.c.id == user.id).
                values(password_hash=hashed_password)
            )
        else:
            # Handle users with no password (e.g., set a default hash)
            default_hashed_password = bcrypt.hashpw(b'', bcrypt.gensalt()).decode('utf-8')
            op.execute(
                users_table.update().
                where(users_table.c.id == user.id).
                values(password_hash=default_hashed_password)
            )

    # 3. Alter password_hash to nullable=False
    op.alter_column('users', 'password_hash', existing_type=sa.String(length=255), nullable=False)

    # 4. Drop the old password column
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
